@testset "Graph coloring" begin

@testset "49 US states + DC" begin
    com = CS.init()

    num_colors = 8
    washington = CS.add_var!(com, 1, num_colors)
    montana = CS.add_var!(com, 1, num_colors)
    maine = CS.add_var!(com, 1, num_colors)
    north_dakota = CS.add_var!(com, 1, num_colors)
    south_dakota = CS.add_var!(com, 1, num_colors)
    wyoming = CS.add_var!(com, 1, num_colors)
    wisconsin = CS.add_var!(com, 1, num_colors)
    idaho = CS.add_var!(com, 1, num_colors)
    vermont = CS.add_var!(com, 1, num_colors)
    minnesota = CS.add_var!(com, 1, num_colors)
    oregon = CS.add_var!(com, 1, num_colors)
    new_hampshire = CS.add_var!(com, 1, num_colors)
    iowa = CS.add_var!(com, 1, num_colors)
    massachusetts = CS.add_var!(com, 1, num_colors)
    nebraska = CS.add_var!(com, 1, num_colors)
    new_york = CS.add_var!(com, 1, num_colors)
    pennsylvania = CS.add_var!(com, 1, num_colors)
    connecticut = CS.add_var!(com, 1, num_colors)
    rhode_island = CS.add_var!(com, 1, num_colors)
    new_jersey = CS.add_var!(com, 1, num_colors)
    indiana = CS.add_var!(com, 1, num_colors)
    nevada = CS.add_var!(com, 1, num_colors)
    utah = CS.add_var!(com, 1, num_colors)
    california = CS.add_var!(com, 1, num_colors)
    ohio = CS.add_var!(com, 1, num_colors)
    illinois = CS.add_var!(com, 1, num_colors)
    washington_dc = CS.add_var!(com, 1, num_colors)
    delaware = CS.add_var!(com, 1, num_colors)
    west_virginia = CS.add_var!(com, 1, num_colors)
    maryland = CS.add_var!(com, 1, num_colors)
    colorado = CS.add_var!(com, 1, num_colors)
    kentucky = CS.add_var!(com, 1, num_colors)
    kansas = CS.add_var!(com, 1, num_colors)
    virginia = CS.add_var!(com, 1, num_colors)
    missouri = CS.add_var!(com, 1, num_colors)
    arizona = CS.add_var!(com, 1, num_colors)
    oklahoma = CS.add_var!(com, 1, num_colors)
    north_carolina = CS.add_var!(com, 1, num_colors)
    tennessee = CS.add_var!(com, 1, num_colors)
    texas = CS.add_var!(com, 1, num_colors)
    new_mexico = CS.add_var!(com, 1, num_colors)
    alabama = CS.add_var!(com, 1, num_colors)
    mississippi = CS.add_var!(com, 1, num_colors)
    georgia = CS.add_var!(com, 1, num_colors)
    south_carolina = CS.add_var!(com, 1, num_colors)
    arkansas = CS.add_var!(com, 1, num_colors)
    louisiana = CS.add_var!(com, 1, num_colors)
    florida = CS.add_var!(com, 1, num_colors)
    michigan = CS.add_var!(com, 1, num_colors)

    states = [washington,montana,maine,north_dakota,south_dakota,wyoming,wisconsin,idaho,vermont,minnesota,oregon,new_hampshire,
    iowa,massachusetts,nebraska,new_york,pennsylvania,connecticut,rhode_island,new_jersey,indiana,nevada,utah,california,ohio,
    illinois,washington_dc,delaware,west_virginia,maryland,colorado,kentucky,kansas,virginia,missouri,arizona,oklahoma,north_carolina,
    tennessee,texas,new_mexico,alabama,mississippi,georgia,south_carolina,arkansas,louisiana,florida,michigan]

    CS.add_constraint!(com, washington != oregon)
    CS.add_constraint!(com, washington != idaho)
    CS.add_constraint!(com, oregon != idaho)
    CS.add_constraint!(com, oregon != nevada)
    CS.add_constraint!(com, oregon != california)
    CS.add_constraint!(com, california != nevada)
    CS.add_constraint!(com, california != arizona)
    CS.add_constraint!(com, nevada != idaho)
    CS.add_constraint!(com, nevada != utah)
    CS.add_constraint!(com, nevada != arizona)
    CS.add_constraint!(com, idaho != montana)
    CS.add_constraint!(com, idaho != wyoming)
    CS.add_constraint!(com, idaho != utah)
    CS.add_constraint!(com, utah != wyoming)
    CS.add_constraint!(com, utah != colorado)
    CS.add_constraint!(com, utah != new_mexico)
    CS.add_constraint!(com, utah != arizona)
    CS.add_constraint!(com, arizona != colorado)
    CS.add_constraint!(com, arizona != new_mexico)
    CS.add_constraint!(com, montana != north_dakota)
    CS.add_constraint!(com, montana != south_dakota)
    CS.add_constraint!(com, montana != wyoming)
    CS.add_constraint!(com, wyoming != south_dakota)
    CS.add_constraint!(com, wyoming != nebraska)
    CS.add_constraint!(com, wyoming != colorado)
    CS.add_constraint!(com, colorado != nebraska)
    CS.add_constraint!(com, colorado != kansas)
    CS.add_constraint!(com, colorado != oklahoma)
    CS.add_constraint!(com, colorado != new_mexico)
    CS.add_constraint!(com, new_mexico != oklahoma)
    CS.add_constraint!(com, new_mexico != texas)
    CS.add_constraint!(com, north_dakota != minnesota)
    CS.add_constraint!(com, north_dakota != south_dakota)
    CS.add_constraint!(com, south_dakota != minnesota)
    CS.add_constraint!(com, south_dakota != iowa)
    CS.add_constraint!(com, south_dakota != nebraska)
    CS.add_constraint!(com, nebraska != iowa)
    CS.add_constraint!(com, nebraska != missouri)
    CS.add_constraint!(com, nebraska != kansas)
    CS.add_constraint!(com, kansas != missouri)
    CS.add_constraint!(com, kansas != oklahoma)
    CS.add_constraint!(com, oklahoma != arkansas)
    CS.add_constraint!(com, oklahoma != texas)
    CS.add_constraint!(com, texas != arkansas)
    CS.add_constraint!(com, texas != louisiana)
    CS.add_constraint!(com, minnesota != wisconsin)
    CS.add_constraint!(com, minnesota != iowa)
    CS.add_constraint!(com, iowa != wisconsin)
    CS.add_constraint!(com, iowa != illinois)
    CS.add_constraint!(com, iowa != missouri)
    CS.add_constraint!(com, missouri != illinois)
    CS.add_constraint!(com, missouri != kentucky)
    CS.add_constraint!(com, missouri != tennessee)
    CS.add_constraint!(com, missouri != arkansas)
    CS.add_constraint!(com, arkansas != tennessee)
    CS.add_constraint!(com, arkansas != mississippi)
    CS.add_constraint!(com, arkansas != louisiana)
    CS.add_constraint!(com, louisiana != mississippi)
    CS.add_constraint!(com, wisconsin != illinois)
    CS.add_constraint!(com, wisconsin != michigan)
    CS.add_constraint!(com, illinois != indiana)
    CS.add_constraint!(com, illinois != kentucky)
    CS.add_constraint!(com, kentucky != indiana)
    CS.add_constraint!(com, kentucky != ohio)
    CS.add_constraint!(com, kentucky != west_virginia)
    CS.add_constraint!(com, kentucky != virginia)
    CS.add_constraint!(com, kentucky != tennessee)
    CS.add_constraint!(com, tennessee != virginia)
    CS.add_constraint!(com, tennessee != north_carolina)
    CS.add_constraint!(com, tennessee != georgia)
    CS.add_constraint!(com, tennessee != alabama)
    CS.add_constraint!(com, tennessee != mississippi)
    CS.add_constraint!(com, mississippi != alabama)
    CS.add_constraint!(com, michigan != indiana)
    CS.add_constraint!(com, michigan != ohio)
    CS.add_constraint!(com, indiana != ohio)
    CS.add_constraint!(com, alabama != georgia)
    CS.add_constraint!(com, alabama != florida)
    CS.add_constraint!(com, ohio != pennsylvania)
    CS.add_constraint!(com, ohio != west_virginia)
    CS.add_constraint!(com, maine != new_hampshire)
    CS.add_constraint!(com, new_hampshire != vermont)
    CS.add_constraint!(com, new_hampshire != massachusetts)
    CS.add_constraint!(com, vermont != massachusetts)
    CS.add_constraint!(com, vermont != new_york)
    CS.add_constraint!(com, massachusetts != new_york)
    CS.add_constraint!(com, massachusetts != rhode_island)
    CS.add_constraint!(com, massachusetts != connecticut)
    CS.add_constraint!(com, connecticut != rhode_island)
    CS.add_constraint!(com, new_york != connecticut)
    CS.add_constraint!(com, new_york != pennsylvania)
    CS.add_constraint!(com, new_york != new_jersey)
    CS.add_constraint!(com, pennsylvania != new_jersey)
    CS.add_constraint!(com, pennsylvania != delaware)
    CS.add_constraint!(com, pennsylvania != maryland)
    CS.add_constraint!(com, pennsylvania != west_virginia)
    CS.add_constraint!(com, new_jersey != delaware)
    CS.add_constraint!(com, maryland != washington_dc)
    CS.add_constraint!(com, maryland != west_virginia)
    CS.add_constraint!(com, maryland != virginia)
    CS.add_constraint!(com, washington_dc != virginia)
    CS.add_constraint!(com, west_virginia != virginia)
    CS.add_constraint!(com, virginia != north_carolina)
    CS.add_constraint!(com, north_carolina != south_carolina)
    CS.add_constraint!(com, south_carolina != georgia)
    CS.add_constraint!(com, georgia != florida)

    # :should be :Min or :Max
    @test_throws ErrorException CS.set_objective!(com, :Minimize, CS.vars_max(states))

    CS.set_objective!(com, :Min, CS.vars_max(states))

    status = CS.solve!(com; keep_logs=true)
    CS.save_logs(com, "graph_color_optimize.json")
    rm("graph_color_optimize.json")

    @test status == :Solved
    @test com.best_sol == 4
    @test all([CS.isfixed(var) for var in states])
    @test maximum([CS.value(var) for var in states]) == 4

end

@testset "49 US states + DC only 3 colors" begin
    com = CS.init()

    num_colors = 3
    washington = CS.add_var!(com, 1, num_colors)
    montana = CS.add_var!(com, 1, num_colors)
    maine = CS.add_var!(com, 1, num_colors)
    north_dakota = CS.add_var!(com, 1, num_colors)
    south_dakota = CS.add_var!(com, 1, num_colors)
    wyoming = CS.add_var!(com, 1, num_colors)
    wisconsin = CS.add_var!(com, 1, num_colors)
    idaho = CS.add_var!(com, 1, num_colors)
    vermont = CS.add_var!(com, 1, num_colors)
    minnesota = CS.add_var!(com, 1, num_colors)
    oregon = CS.add_var!(com, 1, num_colors)
    new_hampshire = CS.add_var!(com, 1, num_colors)
    iowa = CS.add_var!(com, 1, num_colors)
    massachusetts = CS.add_var!(com, 1, num_colors)
    nebraska = CS.add_var!(com, 1, num_colors)
    new_york = CS.add_var!(com, 1, num_colors)
    pennsylvania = CS.add_var!(com, 1, num_colors)
    connecticut = CS.add_var!(com, 1, num_colors)
    rhode_island = CS.add_var!(com, 1, num_colors)
    new_jersey = CS.add_var!(com, 1, num_colors)
    indiana = CS.add_var!(com, 1, num_colors)
    nevada = CS.add_var!(com, 1, num_colors)
    utah = CS.add_var!(com, 1, num_colors)
    california = CS.add_var!(com, 1, num_colors)
    ohio = CS.add_var!(com, 1, num_colors)
    illinois = CS.add_var!(com, 1, num_colors)
    washington_dc = CS.add_var!(com, 1, num_colors)
    delaware = CS.add_var!(com, 1, num_colors)
    west_virginia = CS.add_var!(com, 1, num_colors)
    maryland = CS.add_var!(com, 1, num_colors)
    colorado = CS.add_var!(com, 1, num_colors)
    kentucky = CS.add_var!(com, 1, num_colors)
    kansas = CS.add_var!(com, 1, num_colors)
    virginia = CS.add_var!(com, 1, num_colors)
    missouri = CS.add_var!(com, 1, num_colors)
    arizona = CS.add_var!(com, 1, num_colors)
    oklahoma = CS.add_var!(com, 1, num_colors)
    north_carolina = CS.add_var!(com, 1, num_colors)
    tennessee = CS.add_var!(com, 1, num_colors)
    texas = CS.add_var!(com, 1, num_colors)
    new_mexico = CS.add_var!(com, 1, num_colors)
    alabama = CS.add_var!(com, 1, num_colors)
    mississippi = CS.add_var!(com, 1, num_colors)
    georgia = CS.add_var!(com, 1, num_colors)
    south_carolina = CS.add_var!(com, 1, num_colors)
    arkansas = CS.add_var!(com, 1, num_colors)
    louisiana = CS.add_var!(com, 1, num_colors)
    florida = CS.add_var!(com, 1, num_colors)
    michigan = CS.add_var!(com, 1, num_colors)

    states = [washington,montana,maine,north_dakota,south_dakota,wyoming,wisconsin,idaho,vermont,minnesota,oregon,new_hampshire,
    iowa,massachusetts,nebraska,new_york,pennsylvania,connecticut,rhode_island,new_jersey,indiana,nevada,utah,california,ohio,
    illinois,washington_dc,delaware,west_virginia,maryland,colorado,kentucky,kansas,virginia,missouri,arizona,oklahoma,north_carolina,
    tennessee,texas,new_mexico,alabama,mississippi,georgia,south_carolina,arkansas,louisiana,florida,michigan]

    CS.add_constraint!(com, washington != oregon)
    CS.add_constraint!(com, washington != idaho)
    CS.add_constraint!(com, oregon != idaho)
    CS.add_constraint!(com, oregon != nevada)
    CS.add_constraint!(com, oregon != california)
    CS.add_constraint!(com, california != nevada)
    CS.add_constraint!(com, california != arizona)
    CS.add_constraint!(com, nevada != idaho)
    CS.add_constraint!(com, nevada != utah)
    CS.add_constraint!(com, nevada != arizona)
    CS.add_constraint!(com, idaho != montana)
    CS.add_constraint!(com, idaho != wyoming)
    CS.add_constraint!(com, idaho != utah)
    CS.add_constraint!(com, utah != wyoming)
    CS.add_constraint!(com, utah != colorado)
    CS.add_constraint!(com, utah != new_mexico)
    CS.add_constraint!(com, utah != arizona)
    CS.add_constraint!(com, arizona != colorado)
    CS.add_constraint!(com, arizona != new_mexico)
    CS.add_constraint!(com, montana != north_dakota)
    CS.add_constraint!(com, montana != south_dakota)
    CS.add_constraint!(com, montana != wyoming)
    CS.add_constraint!(com, wyoming != south_dakota)
    CS.add_constraint!(com, wyoming != nebraska)
    CS.add_constraint!(com, wyoming != colorado)
    CS.add_constraint!(com, colorado != nebraska)
    CS.add_constraint!(com, colorado != kansas)
    CS.add_constraint!(com, colorado != oklahoma)
    CS.add_constraint!(com, colorado != new_mexico)
    CS.add_constraint!(com, new_mexico != oklahoma)
    CS.add_constraint!(com, new_mexico != texas)
    CS.add_constraint!(com, north_dakota != minnesota)
    CS.add_constraint!(com, north_dakota != south_dakota)
    CS.add_constraint!(com, south_dakota != minnesota)
    CS.add_constraint!(com, south_dakota != iowa)
    CS.add_constraint!(com, south_dakota != nebraska)
    CS.add_constraint!(com, nebraska != iowa)
    CS.add_constraint!(com, nebraska != missouri)
    CS.add_constraint!(com, nebraska != kansas)
    CS.add_constraint!(com, kansas != missouri)
    CS.add_constraint!(com, kansas != oklahoma)
    CS.add_constraint!(com, oklahoma != arkansas)
    CS.add_constraint!(com, oklahoma != texas)
    CS.add_constraint!(com, texas != arkansas)
    CS.add_constraint!(com, texas != louisiana)
    CS.add_constraint!(com, minnesota != wisconsin)
    CS.add_constraint!(com, minnesota != iowa)
    CS.add_constraint!(com, iowa != wisconsin)
    CS.add_constraint!(com, iowa != illinois)
    CS.add_constraint!(com, iowa != missouri)
    CS.add_constraint!(com, missouri != illinois)
    CS.add_constraint!(com, missouri != kentucky)
    CS.add_constraint!(com, missouri != tennessee)
    CS.add_constraint!(com, missouri != arkansas)
    CS.add_constraint!(com, arkansas != tennessee)
    CS.add_constraint!(com, arkansas != mississippi)
    CS.add_constraint!(com, arkansas != louisiana)
    CS.add_constraint!(com, louisiana != mississippi)
    CS.add_constraint!(com, wisconsin != illinois)
    CS.add_constraint!(com, wisconsin != michigan)
    CS.add_constraint!(com, illinois != indiana)
    CS.add_constraint!(com, illinois != kentucky)
    CS.add_constraint!(com, kentucky != indiana)
    CS.add_constraint!(com, kentucky != ohio)
    CS.add_constraint!(com, kentucky != west_virginia)
    CS.add_constraint!(com, kentucky != virginia)
    CS.add_constraint!(com, kentucky != tennessee)
    CS.add_constraint!(com, tennessee != virginia)
    CS.add_constraint!(com, tennessee != north_carolina)
    CS.add_constraint!(com, tennessee != georgia)
    CS.add_constraint!(com, tennessee != alabama)
    CS.add_constraint!(com, tennessee != mississippi)
    CS.add_constraint!(com, mississippi != alabama)
    CS.add_constraint!(com, michigan != indiana)
    CS.add_constraint!(com, michigan != ohio)
    CS.add_constraint!(com, indiana != ohio)
    CS.add_constraint!(com, alabama != georgia)
    CS.add_constraint!(com, alabama != florida)
    CS.add_constraint!(com, ohio != pennsylvania)
    CS.add_constraint!(com, ohio != west_virginia)
    CS.add_constraint!(com, maine != new_hampshire)
    CS.add_constraint!(com, new_hampshire != vermont)
    CS.add_constraint!(com, new_hampshire != massachusetts)
    CS.add_constraint!(com, vermont != massachusetts)
    CS.add_constraint!(com, vermont != new_york)
    CS.add_constraint!(com, massachusetts != new_york)
    CS.add_constraint!(com, massachusetts != rhode_island)
    CS.add_constraint!(com, massachusetts != connecticut)
    CS.add_constraint!(com, connecticut != rhode_island)
    CS.add_constraint!(com, new_york != connecticut)
    CS.add_constraint!(com, new_york != pennsylvania)
    CS.add_constraint!(com, new_york != new_jersey)
    CS.add_constraint!(com, pennsylvania != new_jersey)
    CS.add_constraint!(com, pennsylvania != delaware)
    CS.add_constraint!(com, pennsylvania != maryland)
    CS.add_constraint!(com, pennsylvania != west_virginia)
    CS.add_constraint!(com, new_jersey != delaware)
    CS.add_constraint!(com, maryland != washington_dc)
    CS.add_constraint!(com, maryland != west_virginia)
    CS.add_constraint!(com, maryland != virginia)
    CS.add_constraint!(com, washington_dc != virginia)
    CS.add_constraint!(com, west_virginia != virginia)
    CS.add_constraint!(com, virginia != north_carolina)
    CS.add_constraint!(com, north_carolina != south_carolina)
    CS.add_constraint!(com, south_carolina != georgia)
    CS.add_constraint!(com, georgia != florida)

    CS.set_objective!(com, :Min, CS.vars_max(states))

    status = CS.solve!(com)

    @test status == :Infeasible
end

end