name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0.4, 1.4.0, '^1.5.0-beta1']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@master
      - name: "Run tests"
        uses: julia-actions/julia-runtest@master
      - name: "Create CodeCov "
        uses: julia-actions/julia-processcoverage@v1
      - name: "Upload CodeCov"  
        uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true